const { plainReqPost, plainReqGet } = require("./reqs/signed_request_plain");
const { encReqPost, encReqGet } = require("./reqs/signed_request_enc");
const {
  createUser,
  resendSignupOTP,
  verifySignupOTP,
} = require("./reqs/create_user");
const {
  resendAnyOtherOTP,
  verifyAnyOtherOTP,
  verifyPin,
  resetPin,
} = require("./reqs/req_others");
const { createUserPin, forgotPin } = require("./reqs/create_user_pin");
const { verifySign } = require("./utils");
const {
  SIGNED_HEADERS,
  DEVICE_ID,
  API_ENDPOINT,
  JWT_TOKENS,
} = require("./constants");
const { getRefreshToken } = require("./reqs/get_refresh_token");

// ----------------------------------------------
// ----------------------------------------------
// ----------------------------------------------

(async () => {
  const usr_data = {
    country_code: "91",
    phone: "1234567890",
  };
  //
  
  await createUser(usr_data);

  const otp_req = {
    otp_req_token: "5524890eb855552691f2d7a7b5c84767",
    otp_req_action: "USER-REGISTER",
  };

  // await resendSignupOTP(usr_data, otp_req);
  await verifySignupOTP(usr_data, otp_req, "117123");

  // -----------------------------------------------------------------------------------
  const tmp_access_token =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MTEyMzQ1Njc4OTBAMDdmNDI0NDAtY2NmNi00ZTU0LWI4ZjEtMTNiYTY5NzAwNDE2IiwiaWF0IjoxNjk0OTUzNjIwLCJuYmYiOjE2OTQ5NTM2MjAsImp0aSI6ImM4YWIwMjQwZDgxNDU1OTA0NTBhNmNjZjRjOTQ5MWJkODlkMjk0ZGVmOTY5OGYzNjYyYmViYTBjMTA4ZDMwNTUiLCJleHAiOjE2OTQ5NzQzMjAsInR5cGUiOiJhY2Nlc3MiLCJmcmVzaCI6ZmFsc2V9.swH-CURx0XOUJLDESNhlAquIt4A7Q8Sur23WPXcyQQ4";

  JWT_TOKENS.access_tmp = tmp_access_token;

  // // // pin is neither stored nor logged anywhere in app (neither in-memory nor persistent)
  // await createUserPin(usr_data, JWT_TOKENS.access_tmp, "1234");

  // -----------------------------------------------------------------------------------
  const access_token =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MTEyMzQ1Njc4OTBAMDdmNDI0NDAtY2NmNi00ZTU0LWI4ZjEtMTNiYTY5NzAwNDE2IiwiaWF0IjoxNjk0OTYyNDAwLCJuYmYiOjE2OTQ5NjI0MDAsImp0aSI6ImQ1MDJjMWExYTRjNTI2MDRhNGNjNmU5YzY4MmUwODFkYTQxOGMzODgwMzMwZjVmZWJhNGQ2NjI0YmMzMTExYTIiLCJleHAiOjE2OTUwNzIyMDAsInR5cGUiOiJhY2Nlc3MiLCJmcmVzaCI6dHJ1ZX0.YIrG83lO8LEYzaQW3O9DTTzigwO9MjWxbkJSScbqU7o";
  const refresh_token =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MTEyMzQ1Njc4OTBAMDdmNDI0NDAtY2NmNi00ZTU0LWI4ZjEtMTNiYTY5NzAwNDE2IiwiaWF0IjoxNjk0OTYyMDg4LCJuYmYiOjE2OTQ5NjIwODgsImp0aSI6IjA2OWRmMTRhNTc1NTg3MDRkYmE3OTdlOGRjNTQ0MDQxNmU5OGMyN2Y2MTdmNGNiODRlZDUxMDRkNmI0ZWRmYzUiLCJleHAiOjIzMjU3MDE4ODgsInR5cGUiOiJyZWZyZXNoIn0.CLCFgNP8CU374i2T0VHmmKqa_hLlTqdZbtXicSDCOc8";

  JWT_TOKENS.access = access_token;
  JWT_TOKENS.refresh = refresh_token;

  // this key is generated in createUserPin.. has to be stored in app keystore/keychain securely
  const secretKey = "eqQNBJwVqtkOX5S6u//185p1vnS5xv9HExlNWwyTDlk=";

  // -----------------------------------------------------------------------------------
  // await getRefreshToken(JWT_TOKENS.refresh);

  // -----------------------------------------------------------------------------------
  // otp_req is generated by some action which requires otp-verification (like create_user above)
  // await resendAnyOtherOTP(usr_data, secretKey, JWT_TOKENS.access, otp_req);
  // await verifyAnyOtherOTP(usr_data,secretKey, JWT_TOKENS.access, otp_req,"053503");

  // -----------------------------------------------------------------------------------

  // await plainReqPost(secretKey, JWT_TOKENS.access);
  // await plainReqGet(secretKey, JWT_TOKENS.access);
  // await encReqPost(secretKey, JWT_TOKENS.access);
  // await encReqGet(secretKey, JWT_TOKENS.access);

  // these 2 func will return new JWT_TOKENS.access
  // await verifyPin(usr_data, secretKey, JWT_TOKENS.refresh, "1234");
  // await resetPin(usr_data, secretKey, JWT_TOKENS.refresh, "1236", "1234");

  // -----------------------------------------------------------------------------------
  // await forgotPin(usr_data);

  // forgot pin will return a url with <src_req_token> <token>
  // http://127.0.0.1/v1/pin/forgot-create?src_req_token=f3cc82c80e56558e89bf15aa9fb86fbb&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MTEyMzQ1Njc4OTBAMDdmNDI0NDAtY2NmNi00ZTU0LWI4ZjEtMTNiYTY5NzAwNDE2IiwiaWF0IjoxNjk0OTU2NTgxLCJuYmYiOjE2OTQ5NTY1ODEsImp0aSI6IjlkNGRmYTUyZjVhYTYzYWFhYzY3ZjMzYmM3NDg3ZDNlMDBkOTdhZGJhNjUxZjM4N2U5Nzg5MDA2MjRhOWFiYzEiLCJleHAiOjE2OTUwNjYzODEsInR5cGUiOiJhY2Nlc3MiLCJmcmVzaCI6ZmFsc2V9.3w-fXph0z5-pwp7XG7DAg98-E4fyB0k05mC062WrKCo
  const tmp_access_token2 =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MTEyMzQ1Njc4OTBAMDdmNDI0NDAtY2NmNi00ZTU0LWI4ZjEtMTNiYTY5NzAwNDE2IiwiaWF0IjoxNjk0OTYyNDk2LCJuYmYiOjE2OTQ5NjI0OTYsImp0aSI6ImM0ODk3NWMxMmJiZTYwNWY5YTY2N2I4N2Q0NmUyYzZjZjBiMGUyMTA2ZTA4Yjk1ZjE3MWExYTRmOGMzMjMyNTkiLCJleHAiOjE2OTUwNzIyOTYsInR5cGUiOiJhY2Nlc3MiLCJmcmVzaCI6ZmFsc2UsImVwaGVtZXJhbCI6dHJ1ZX0.DxFfJgZkZ7o2SLWQz7Ww13D83CxJvuWzHKEgj_yzWCU";
  const src_req_token = "e5f485abadb9998d59a38ad0f84df617";

  // await createUserPin(usr_data, tmp_access_token2, "1236", src_req_token);
})();